os:
- linux
services:
- docker
- postgresql
addons:
  postgresql: "9.2"
language: node_js
node_js:
- 8.9.4
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=8.9.4
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - secure: Z7OGSQOm/M1r80BrcJwneXJ8yfWS5pX+e+lodspY0u22f1J3KAFF2G5hUgPxYOjFv+DpIcWsTyVo8QtfZAyFdcTsHfKjAHi4gKX1fbnWqWv8zwEj3lRyNWmfABCGaqdZXfZy6rOyIGxuP2iwxAL3x36obhgBVtwJuAyS2rKP5bZxBbWZbbum1inRYr9kAyCaBQxKB6YiiWcNrMY3pq91CuTL/qED903V/vSzkUZ5K09wjK8YggyXhV6wvr+1MSh/+1y9PDQJczESMItPSlsP7iLe8V4mqBwmYZ8FDQn6KolgPv+no/lkxh5LKuKsl/WsQ8D0yyySuf8/ROzDK0gc31w2gtSVMotuI+AbbKZ4sB2jOK+Ad0u/pDvj9aCYYhm0lR5EON0Fz/BTZNESStnrk3EAQ4lsPfmXjLlRU8209Fnjt2BxghIJJ6NYKLcTUL6hohg8MpCkKJSTNuEdDjzZ8I0kD2cuoJuLv9d0S4pm8a4RhIRNffQ6VsDWQp9qlbjmgZrlXGVjMxwCLVERsDujlfiq0/Gnf14s/m/pQfggVXLNgi2LT78bpEpiVwC+qiFIWR2eDHIN4V1G7F2KYJkMEsaDs2QRev3Jr7/N21+uETqXuj2iSe9+udEBFFdUqErIG95I5z3Krkk/UFvKy5+DYCLqTUP9U65cATxbm4sGqUA=
  - secure: Q+EyI35wixZbdhbYtIP+jB86Zdh6vT44rqAmpNTJ0pOgj2zVtD5u6hbwhKFwKSo7yiMBuGl1yECbfe05cBYIZYTGV+ULGF0G2dxs8u1hx2wBbGuMbMrtNIABO4ic8norKhpe6fPPtQ9ps/Tbv0y7Kq+IYjlezfg4b+dShGx/8a/8UxZ3S2Hb9BCrqK05rXwMbnoUg6FnBj5uFN1ju8aWcrutzvaq55PP5weCQt9LCA0zeIAjwPVAOpZXEhlW/W19P+VcKBrCawUNaYQ1wXZFT/kt3YVZnCJgqyOgem8u63bUtHJUY7FNsP8w9yu5XxKA7phMHT1eBn+vvyPGoHLbS1/Z2xfLCVndPW3hx0pRPEhkVPQjoU6Bfxi0LSTovPe7DoQWUB3F7/VUwegrpqefJX6qdX5v06RISdLbGCG5c/1qCY6dDBRG7AiXNa9RfVO5Z78tO6rIH0xXYlFqaiPMN3Hv7ZvPY0GfTAwqOYBcxzDk3/XqaPjJF0ba5lpq/0xnVy4A3VKV98SOMGyqBxbWuivXStLB0OIy9A3SWMF0WutQUAhsHQ/BuxW4iHnz+3W60RgeYzkFgsKQMrIUxGkfVvf//kZWFYPkSL+QSQVpPMvzJz/n8svW6tgb6Ni29FqNVdPJHh4o62PdZLA3yDnfAVX9jU8fWkX9xXyMHznrjQo=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add bower gulp-cli
install:
- yarn install
- bower install
before_script:
  - psql -c "CREATE ROLE travisSnovak WITH PASSWORD 'travis-snovak-pass' SUPERUSER CREATEDB INHERIT LOGIN;" -U postgres
  - psql -c 'CREATE database snovak;' -U postgres
  - psql -c 'ALTER DATABASE snovak OWNER TO travisSnovak' -U postgres
  - psql -c 'ALTER DATABASE snovak OWNER TO travisSnovak' -U postgres
  - psql -c 'GRANT CREATE ON DATABASE snovak TO travisSnovak;' -U postgres
script:
- chmod +x mvnw
- "./mvnw clean test -Dspring.profiles.active=travis"
- gulp test
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
